use std::{
    collections::{HashMap, HashSet},
    path::{Path, PathBuf},
};

use convert_case::Casing as _;
use quote::quote;
use rayon::iter::{IntoParallelRefIterator, ParallelIterator as _};

use crate::utils::algorithms_by_llms::{DependencySortable, sort_by_dependencies};

/// generates Rust bindings from the C (not C++) headers.
///
/// ## Parameters
///
/// - `headers_folder`: The folder containing the C headers (`.h` files) to
///   generate bindings for. Currently, headers in subfolders are not scanned.
/// - `output_folder`: The folder where the generated bindings will be written
///   to. Each `.h` file will have a corresponding `*.rs` file generated in this
///   folder.
///
/// ## Description
///
/// This function generates Rust bindings for the C headers found in the
/// specified `headers_folder`. Each header file will have a corresponding Rust
/// file generated in the `output_folder`.
///
/// ## Performance
///
/// The current implementation is inefficient:
/// - We use `bindgen` to generate bindings for each header file individually,
///   which duplicates the effort of parsing common headers multiple times.
/// - We parse the rust code generated by `bindgen` back to token streams again
///   for processing.
///
/// Luckily, this function is only called during the build process, which does
/// not happen a lot.
///
/// The reason I currently choose this approach is that:
/// - I don't want to waste development time here.
/// - `bindgen` is battle-tested, while rolling a custom parser definitely will
///   shoot myself in the foot.
pub fn generate_bindings_for_c_headers(
    headers_folder: impl Into<PathBuf>,
    output_folder: impl Into<PathBuf>,
) {
    if let Err(err) = generate_bindings_for_c_headers_inner(headers_folder, output_folder) {
        panic!("Failed to generate bindings for C headers: {}", err);
    }
}

const COLORSPACE_HEADER_NAME: &str = "ofx-native-v1.5_aces-v1.3_ocio-v2.3";

fn generate_bindings_for_c_headers_inner(
    headers_folder: impl Into<PathBuf>,
    output_folder: impl Into<PathBuf>,
) -> Result<(), Box<dyn std::error::Error>> {
    let headers_folder = headers_folder.into();
    let output_folder = output_folder.into();

    let headers = Header::headers_from_folder(&headers_folder)
        .map_err(|err| format!("Failed to collect headers: {}", err))?;
    let headers = sort_by_dependencies(headers);
    let deduplicated_syn_files =
        deduplicate(&headers).map_err(|err| format!("Failed to deduplicate headers: {}", err))?;

    for header in headers {
        let mod_name = &header.mod_name_snake_case;
        let output_path = output_folder.join(format!("{}.rs", mod_name));
        let syn_file = deduplicated_syn_files
            .get(&header.name)
            .expect("deduplicated_syn_files should contain the mod_name");
        let mut code = prettyplease::unparse(syn_file);
        if let Some(additional_rust_code) = &header.additional_rust_code {
            code.push('\n');
            code.push_str(additional_rust_code);
        }
        std::fs::write(&output_path, code)?;
    }

    Ok(())
}

pub(crate) struct Header {
    /// without the `.h` extension, with the `ofx` prefix, e.g.
    /// `ofxImageEffect`.
    pub name: String,
    /// without the `ofx` prefix, in snake case, e.g. `image_effect`.
    pub mod_name_snake_case: String,
    /// without the `.h` extension, with the `ofx` prefix, e.g.
    /// `ofxImageEffect`.
    pub included_headers: HashSet<String>,
    /// Unfortunately even though this is not a proc-macro, we still can't send
    /// `syn` or `proc_macro2` values across threads.
    pub bindgen_generated_rust_code: String,

    pub additional_rust_code: Option<String>,
}

impl Header {
    fn headers_from_folder(
        headers_folder: impl Into<PathBuf>,
    ) -> Result<Vec<Self>, Box<dyn std::error::Error + Send + Sync>> {
        let headers_folder = headers_folder.into();

        let mut entries: Vec<(std::fs::DirEntry, String)> = vec![];
        for entry in std::fs::read_dir(&headers_folder)? {
            let entry = entry?;
            let path = entry.path();
            if !entry.file_type()?.is_file() || path.extension().is_none_or(|ext| ext != "h") {
                continue;
            }
            let name = path
                .file_stem()
                .ok_or_else(|| format!("Failed to get file stem for path: {:?}", path))?
                .to_string_lossy()
                .to_string();
            if !name.starts_with("ofx") || name == COLORSPACE_HEADER_NAME {
                continue;
            }
            entries.push((entry, name));
        }

        let headers: Vec<Header> = entries
            .par_iter()
            .map(
                |(entry, name)| -> Result<Header, Box<dyn std::error::Error + Send + Sync>> {
                    let path = entry.path();

                    let c_code = std::fs::read_to_string(&path)?;
                    Self::from_c_code(&headers_folder, &path, name, &c_code)
                },
            )
            .collect::<Result<Vec<_>, _>>()?;

        Ok(headers)
    }

    fn from_c_code(
        headers_folder: &Path,
        path: &Path,
        name: &str,
        c_code: &str,
    ) -> Result<Self, Box<dyn std::error::Error + Send + Sync>> {
        let name_snake_case = name
            .strip_prefix("ofx")
            .unwrap()
            .to_case(convert_case::Case::Snake);

        let mut included_headers = HashSet::new();
        for line in c_code.lines() {
            static INCLUDE_PREFIX: &str = "#include \"";
            static INCLUDE_SUFFIX: &str = ".h\"";

            if line.starts_with(INCLUDE_PREFIX) && line.ends_with(INCLUDE_SUFFIX) {
                let include_name =
                    line[(INCLUDE_PREFIX.len())..(line.len() - INCLUDE_SUFFIX.len())].to_string();

                if include_name == COLORSPACE_HEADER_NAME {
                    continue;
                }
                included_headers.insert(include_name);
            }
        }

        let mut additional_rust_code: Option<String> = None;
        if name == "ofxCore" {
            let mut additional_lines: Vec<String> = vec![];

            for line in c_code.lines() {
                const PREFIX: &str = "#define kOfxStat";
                if !line.starts_with(PREFIX) {
                    continue;
                }
                let rest = line[PREFIX.len()..].trim();
                let (name, rest) = rest
                    .split_once(' ')
                    .ok_or_else(|| format!("Failed to split line: {}", line))?;
                let num = extract_number(rest)
                    .ok_or_else(|| format!("Failed to extract number from line: {}", line))?;
                additional_lines.push(format!("pub const kOfxStat{}: OfxStatus = {};", name, num));
            }
            additional_rust_code = Some(additional_lines.join("\n"));
        } else {
            included_headers.insert("ofxCore".to_string());
        }

        Ok(Header {
            name: name.to_owned(),
            mod_name_snake_case: name_snake_case,
            included_headers,
            bindgen_generated_rust_code: bindgen::Builder::default()
                .header("stdbool.h")
                .header(headers_folder.join("ofxCore.h").to_string_lossy())
                .header(path.to_string_lossy())
                .allowlist_function("") // blocking all
                .allowlist_type("Ofx.+")
                .allowlist_var("kOfx.+")
                .generate_cstr(true)
                .generate()?
                .to_string(),
            additional_rust_code,
        })
    }
}

fn deduplicate(
    headers: &[Header],
) -> Result<HashMap<String, syn::File>, Box<dyn std::error::Error>> {
    // item name -> `mod_name_snake_case` of the header file that defines it
    let mut seen_names: HashMap<String, String> = HashMap::new();

    let mut deduplicated_syn_files: HashMap<String, syn::File> = HashMap::new();

    for header in headers {
        // `mod_name_snake_case` -> item names
        let mut to_use: HashMap<String, HashSet<String>> = HashMap::new();
        let mut dedup_items: Vec<syn::Item> = vec![];

        let syn_file = syn::parse_file(&header.bindgen_generated_rust_code)?;

        for item in &syn_file.items {
            let ident = match item {
                syn::Item::Const(item_const) => item_const.ident.clone(),
                syn::Item::Fn(item_fn) => item_fn.sig.ident.clone(),
                syn::Item::Struct(item_struct) => item_struct.ident.clone(),
                syn::Item::Type(item_type) => item_type.ident.clone(),
                syn::Item::Enum(_)
                | syn::Item::ExternCrate(_)
                | syn::Item::ForeignMod(_)
                | syn::Item::Impl(_)
                | syn::Item::Macro(_)
                | syn::Item::Mod(_)
                | syn::Item::Static(_)
                | syn::Item::Trait(_)
                | syn::Item::TraitAlias(_)
                | syn::Item::Union(_)
                | syn::Item::Use(_) => {
                    panic!("unexpected item: {}", quote! { #item })
                }
                syn::Item::Verbatim(_) => panic!("unexpected verbatim item: {}", quote! { #item }),
                _ => panic!("unexpected unknown item: {}", quote! { #item }),
            };
            let name = ident.to_string();
            if name == "_" {
                dedup_items.push(item.clone());
                continue;
            } else if name == "kOfxStatOK" {
                // included in `additional_rust_code`.
                continue;
            }

            if let Some(mod_name) = seen_names.get(&name) {
                to_use
                    .entry(mod_name.clone())
                    .or_default()
                    .insert(name.clone());
            } else {
                seen_names.insert(name.clone(), header.mod_name_snake_case.clone());
                dedup_items.push(item.clone());
            }
        }

        let mut use_items: Vec<(String, syn::Item)> = vec![];
        for (mod_name, names) in to_use {
            let mut names: Vec<&String> = names.iter().collect();
            names.sort();

            let use_item = make_use_item(&mod_name, &names);

            use_items.push((mod_name.clone(), syn::Item::Use(use_item)));
        }
        use_items.sort_by(|(mod_name_a, _), (mod_name_b, _)| mod_name_a.cmp(mod_name_b));

        dedup_items.splice(0..0, use_items.into_iter().map(|(_, item)| item));

        let new_file = syn::File {
            items: dedup_items,
            ..syn_file
        };

        deduplicated_syn_files.insert(header.name.clone(), new_file);
    }

    Ok(deduplicated_syn_files)
}

fn make_use_item(mod_name: &str, names: &[&String]) -> syn::ItemUse {
    syn::ItemUse {
        attrs: vec![],
        vis: syn::Visibility::Inherited,
        use_token: Default::default(),
        leading_colon: None,
        tree: syn::UseTree::Path(syn::UsePath {
            ident: syn::Ident::new("super", proc_macro2::Span::call_site()),
            colon2_token: Default::default(),
            tree: Box::new(syn::UseTree::Path(syn::UsePath {
                ident: syn::Ident::new(mod_name, proc_macro2::Span::call_site()),
                colon2_token: Default::default(),
                tree: Box::new(syn::UseTree::Group(syn::UseGroup {
                    brace_token: Default::default(),
                    items: names
                        .iter()
                        .map(|name| {
                            syn::UseTree::Name(syn::UseName {
                                ident: syn::Ident::new(name, proc_macro2::Span::call_site()),
                            })
                        })
                        .collect(),
                })),
            })),
        }),
        semi_token: Default::default(),
    }
}

impl DependencySortable for Header {
    fn name(&self) -> &str {
        &self.name
    }

    fn dependencies(&self) -> &HashSet<String> {
        &self.included_headers
    }
}

fn extract_number(input: &str) -> Option<u32> {
    let mut i_start = -1;
    let mut i_end = -1;

    for (i, ch) in input.chars().enumerate() {
        if ch.is_ascii_digit() {
            if i_start == -1 {
                i_start = i as i32;
            }
            i_end = i as i32;
        } else if i_start != -1 {
            break;
        }
    }

    if i_start == -1 || i_end == -1 {
        None
    } else {
        let number_str = &input[i_start as usize..=i_end as usize];
        Some(number_str.parse::<u32>().unwrap())
    }
}
