[workspace]
resolver = "3"
members = [
  "crates/openfx",
  "crates/openfx-internal-macros",
  "crates/private/openfx-codegen",
  "examples/ofx-guide-example-plugins-layer-sys",
  "examples/ofx-guide-example-plugins-layer-low",
]

[workspace.package]
version = "0.3.0"
license = "BSD-3-Clause"
repository = "https://github.com/kreantio/openfx-rs"

[workspace.lints]

[workspace.dependencies]
openfx = { path = "crates/openfx", version = "0.3.0" }
openfx-codegen = { path = "crates/openfx-codegen", version = "0.3.0" }
openfx-internal-macros = { path = "crates/openfx-internal-macros", version = "0.3.0" }

bindgen = "0.72.1"
clap = "4.6.6"
convert_case = "0.11.0"
prettyplease = "0.3.0"
proc-macro2 = "1.0.107"
quote = "1.0.47"
rayon = "1.12.0"
serde_json = "1.0.151"
syn = "3.0.3"
tracing = "0.1.44"
