use std::{
    collections::{BTreeMap, HashMap, HashSet},
    path::{Path, PathBuf},
};

use convert_case::Casing as _;
use quote::{ToTokens as _, quote};
use rayon::iter::{IntoParallelRefIterator, ParallelIterator as _};

use crate::{
    CodegenConfig,
    vibe_zone::utils::algorithms_by_llms::{
        DependencySortable, sort_by_dependencies, strip_common_prefix,
    },
};

pub struct Options {
    pub config: CodegenConfig,
    pub headers_folder: PathBuf,
    pub output_folder: PathBuf,
    pub output_folder_c: PathBuf,
    pub output_folder_intermediate: PathBuf,
}

/// generates Rust bindings from the C (not C++) headers.
///
/// ## Parameters
///
/// - `headers_folder`: The folder containing the C headers (`.h` files) to
///   generate bindings for. Currently, headers in subfolders are not scanned.
/// - `output_folder`: The folder where the generated bindings will be written
///   to. Each `.h` file will have a corresponding `*.rs` file generated in this
///   folder.
///
/// ## Description
///
/// This function generates Rust bindings for the C headers found in the
/// specified `headers_folder`. Each header file will have a corresponding Rust
/// file generated in the `output_folder`.
///
/// ## Performance
///
/// The current implementation is inefficient:
/// - We use `bindgen` to generate bindings for each header file individually,
///   which duplicates the effort of parsing common headers multiple times.
/// - We parse the rust code generated by `bindgen` back to token streams again
///   for processing.
///
/// Luckily, this function is only called during the build process, which does
/// not happen a lot.
///
/// The reason I currently choose this approach is that:
/// - I don't want to waste development time here.
/// - `bindgen` is battle-tested, while rolling a custom parser definitely will
///   shoot myself in the foot.
pub fn generate_bindings_for_c_headers(opts: Options) {
    if let Err(err) = generate_bindings_for_c_headers_inner(opts) {
        panic!("Failed to generate bindings for C headers: {}", err);
    }
}

const COLORSPACE_HEADER_NAME: &str = "ofx-native-v1.5_aces-v1.3_ocio-v2.3";

fn generate_bindings_for_c_headers_inner(opts: Options) -> Result<(), Box<dyn std::error::Error>> {
    let headers = Header::headers_from_folder(&opts.headers_folder)
        .map_err(|err| format!("Failed to collect headers: {}", err))?;
    let headers = sort_by_dependencies(headers);
    let ProcessOutput {
        deduplicated_syn_files,
        checks_syn_files,
        root_item_idents_per_header,
        c_enums,
        suites,
    } = process(&headers).map_err(|err| format!("Failed to process headers: {}", err))?;

    std::fs::create_dir_all(&opts.output_folder_c)?;

    let GenCBindingsOutput { statuses } =
        gen_c_bindings(&opts.output_folder, &headers, &deduplicated_syn_files)?;
    gen_c_bindings_checks(&opts.output_folder, &headers, &checks_syn_files)?;

    gen_low_statuses(&opts.output_folder_c, statuses)?;
    gen_low_enums_from_c(&opts.output_folder_c, c_enums)?;
    gen_suites(&opts.config, &opts.output_folder_c, suites)?;

    gen_data_root_idents(
        &opts.output_folder_intermediate,
        root_item_idents_per_header,
    )?;

    Ok(())
}

struct GenCBindingsOutput {
    statuses: HashSet<String>,
}

fn gen_c_bindings(
    output_folder: &Path,
    headers: &[Header],
    deduplicated_syn_files: &std::collections::HashMap<String, syn::File>,
) -> Result<GenCBindingsOutput, Box<dyn std::error::Error>> {
    let mut statuses: HashSet<String> = HashSet::new();

    for header in headers {
        let mod_name = &header.mod_name_snake_case;
        let output_path = output_folder.join(format!("{}.rs", mod_name));

        let syn_file = deduplicated_syn_files.get(&header.name).ok_or_else(|| {
            format!(
                "`deduplicated_syn_files` should contain the header with name `{}`",
                header.name
            )
        })?;
        let mut code = prettyplease::unparse(syn_file);
        if let Some(additional_rust_code) = &header.additional_rust_code {
            code.push('\n');
            code.push_str(additional_rust_code);
        }
        std::fs::write(&output_path, code)?;

        if !header.additional_info.statuses.is_empty() {
            statuses.extend(header.additional_info.statuses.clone());
        }
    }

    Ok(GenCBindingsOutput { statuses })
}

fn gen_c_bindings_checks(
    output_folder: &Path,
    headers: &[Header],
    checks_syn_files: &std::collections::HashMap<String, syn::File>,
) -> Result<(), Box<dyn std::error::Error>> {
    let mut headers: Vec<&Header> = headers.iter().collect();
    headers.sort_by(|a, b| a.name.cmp(&b.name));

    let mut items: Vec<syn::Item> = vec![];
    let mut seen_item_codes: HashSet<String> = HashSet::new();

    for header in headers {
        let checks_syn_file = checks_syn_files.get(&header.name).ok_or_else(|| {
            format!(
                "`check_syn_files` should contain the header with name `{}`",
                header.name
            )
        })?;

        for item in &checks_syn_file.items {
            let item_code = quote! { #item }.to_string();
            if seen_item_codes.contains(&item_code) {
                continue;
            }
            seen_item_codes.insert(item_code);
            items.push(item.clone());
        }
    }

    std::fs::write(
        output_folder.join("_checks.rs"),
        prettyplease::unparse(&syn::File {
            shebang: None,
            frontmatter: None,
            attrs: vec![],
            items,
        }),
    )?;

    Ok(())
}

fn gen_low_statuses(
    output_folder_c: &Path,
    statuses: HashSet<String>,
) -> Result<(), Box<dyn std::error::Error>> {
    let mut statuses: Vec<String> = statuses.into_iter().collect();
    statuses.sort();
    let status_sys_ident = statuses
        .iter()
        .map(|status| {
            syn::Ident::new(
                &format!("kOfxStat{}", status),
                proc_macro2::Span::call_site(),
            )
        })
        .collect::<Vec<_>>();
    let statuses = statuses
        .iter()
        .map(|status| syn::Ident::new(status, proc_macro2::Span::call_site()))
        .collect::<Vec<_>>();

    let code = quote! {
        pub enum Status {
            #(#statuses,)*
            Unknown(crate::sys::generic::core::OfxStatus),
        }
        impl From<crate::sys::generic::core::OfxStatus> for Status {
            fn from(status: crate::sys::generic::core::OfxStatus) -> Self {
                match status {
                    #(crate::sys::generic::core::#status_sys_ident => Self::#statuses,)*
                    _ => Self::Unknown(status),
                }
            }
        }
        impl From<Status> for crate::sys::generic::core::OfxStatus {
            fn from(status: Status) -> Self {
                match status {
                    #(Status::#statuses => crate::sys::generic::core::#status_sys_ident,)*
                    Status::Unknown(status) => status,
                }
            }
        }
    };
    std::fs::write(
        output_folder_c.join("low_statuses.rs"),
        prettyplease::unparse(&syn::parse2(code)?),
    )?;

    Ok(())
}

fn gen_low_enums_from_c(
    output_folder_c: &Path,
    c_enums: HashMap<String, HashSet<String>>,
) -> Result<(), Box<dyn std::error::Error>> {
    let mut output_inner = proc_macro2::TokenStream::new();

    let mut c_enums = c_enums.into_iter().collect::<Vec<_>>();
    c_enums.sort_by(|a, b| a.0.cmp(&b.0));

    for (enum_name, vars) in c_enums {
        let simple_enum_name = enum_name
            .strip_prefix("Ofx")
            .ok_or("Enum name should start with \"Ofx\".")?;

        let enum_name = syn::Ident::new(&enum_name, proc_macro2::Span::call_site());
        let simple_enum_name = syn::Ident::new(simple_enum_name, proc_macro2::Span::call_site());

        let mut vars = vars.into_iter().collect::<Vec<_>>();
        vars.sort();

        let simple_vars = strip_common_prefix(&vars);

        let vars: Vec<syn::Ident> = vars
            .iter()
            .map(|v| syn::Ident::new(v, proc_macro2::Span::call_site()))
            .collect();
        let simple_vars: Vec<syn::Ident> = simple_vars
            .iter()
            .map(|v| syn::Ident::new(v, proc_macro2::Span::call_site()))
            .collect();

        output_inner.extend(quote! {
            #[sys(#enum_name)]
            enum #simple_enum_name {
                #(
                    #[sys(#vars)]
                    #simple_vars,
                )*
            }
        });
    }

    let output_inner = prettyplease::unparse(&syn::parse2(output_inner)?)
        .lines()
        .map(|l| format!("    {}", l))
        .collect::<Vec<_>>()
        .join("\n");

    std::fs::write(
        output_folder_c.join("low_enums_from_c.rs"),
        format!(
            "openfx_internal_macros::low_make_property_enums_from_c! {{
{output_inner}
}}"
        ),
    )?;

    Ok(())
}

fn gen_suites(
    confg: &CodegenConfig,
    output_folder_c: &Path,
    suites: HashMap<String, HashSet<String>>,
) -> Result<(), Box<dyn std::error::Error>> {
    let mut suite_names: Vec<String> = suites.keys().cloned().collect();
    suite_names.sort();
    let simple_names: Vec<String> = suite_names
        .iter()
        .map(|name| {
            name.strip_prefix("Ofx")
                .ok_or("Suite name should start with \"Ofx\".")
                .map(str::to_owned)
        })
        .collect::<Result<_, _>>()?;

    let simple_idents: Vec<syn::Ident> = simple_names
        .iter()
        .map(|name| syn::Ident::new(name, proc_macro2::Span::call_site()))
        .collect();

    // low_suites_plugin
    {
        let mut output = proc_macro2::TokenStream::new();

        for (name, simple_ident) in suite_names.iter().zip(simple_idents.iter()) {
            let special_case = &confg.suites.special_cases.get(&simple_ident.to_string());
            let fns_to_omit = special_case.and_then(|sc| sc.omit_functions.as_ref());

            let full_ident = syn::Ident::new(name, proc_macro2::Span::call_site());
            let mut fns: Vec<syn::Ident> = suites[name]
                .iter()
                .filter(|v| fns_to_omit.is_none_or(|o| !o.contains(*v)))
                .map(|v| {
                    syn::Ident::new(
                        &v.to_case(convert_case::Case::Snake),
                        proc_macro2::Span::call_site(),
                    )
                })
                .collect();
            fns.sort();

            output.extend(quote! {
                openfx_internal_macros::low_make_suite_struct!(#simple_ident:#full_ident: #(#fns,)*);
            });
        }

        std::fs::write(
            output_folder_c.join("low_suites_plugin.rs"),
            prettyplease::unparse(&syn::parse2(output)?),
        )?;
    }

    // low_plugin_impl_host_for_fetch_suites
    {
        let mut output = proc_macro2::TokenStream::new();

        for simple_ident in &simple_idents {
            let special_case = &confg.suites.special_cases.get(&simple_ident.to_string());

            if let Some(corrected_k_name) = special_case.and_then(|sc| sc.key_name.as_deref()) {
                let corrected_k_ident =
                    syn::Ident::new(corrected_k_name, proc_macro2::Span::call_site());
                output.extend(quote! {
                    openfx_internal_macros::low_plugin_impl_host_for_fetch_suite!(#simple_ident @ #corrected_k_ident);
                });
            } else {
                output.extend(quote! {
                    openfx_internal_macros::low_plugin_impl_host_for_fetch_suite!(#simple_ident);
                });
            }
        }

        std::fs::write(
            output_folder_c.join("low_plugin_impl_host_for_fetch_suites.rs"),
            prettyplease::unparse(&syn::parse2(output)?),
        )?;
    }

    Ok(())
}

fn gen_data_root_idents(
    output_folder_im: &Path,
    root_item_idents_per_header: HashMap<String, HashSet<String>>,
) -> Result<(), Box<dyn std::error::Error>> {
    let path = output_folder_im.join("root_item_idents_per_header.json");

    let mut stable_map: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for (mod_name, idents) in root_item_idents_per_header {
        let mut idents: Vec<String> = idents.into_iter().collect();
        idents.sort();
        stable_map.insert(mod_name, idents);
    }

    let json = serde_json::to_string_pretty(&stable_map)?;
    std::fs::write(path, json)?;

    Ok(())
}

pub(crate) struct Header {
    /// without the `.h` extension, with the `ofx` prefix, e.g.
    /// `ofxImageEffect`.
    pub name: String,
    /// without the `ofx` prefix, in snake case, e.g. `image_effect`.
    pub mod_name_snake_case: String,
    /// without the `.h` extension, with the `ofx` prefix, e.g.
    /// `ofxImageEffect`.
    pub included_headers: HashSet<String>,
    /// Unfortunately even though this is not a proc-macro, we still can't send
    /// `syn` or `proc_macro2` values across threads.
    pub bindgen_generated_rust_code: String,

    pub additional_rust_code: Option<String>,
    pub additional_info: AdditionalInfo,
}

#[derive(Default)]
pub(crate) struct AdditionalInfo {
    pub statuses: HashSet<String>,
}

impl Header {
    fn headers_from_folder(
        headers_folder: impl Into<PathBuf>,
    ) -> Result<Vec<Self>, Box<dyn std::error::Error + Send + Sync>> {
        let headers_folder = headers_folder.into();

        let mut entries: Vec<(std::fs::DirEntry, String)> = vec![];
        for entry in std::fs::read_dir(&headers_folder)? {
            let entry = entry?;
            let path = entry.path();
            if !entry.file_type()?.is_file() || path.extension().is_none_or(|ext| ext != "h") {
                continue;
            }
            let name = path
                .file_stem()
                .ok_or_else(|| format!("Failed to get file stem for path: {:?}", path))?
                .to_string_lossy()
                .to_string();
            if !name.starts_with("ofx") || name == COLORSPACE_HEADER_NAME {
                continue;
            }
            entries.push((entry, name));
        }

        let headers: Vec<Header> = entries
            .par_iter()
            .map(
                |(entry, name)| -> Result<Header, Box<dyn std::error::Error + Send + Sync>> {
                    let path = entry.path();

                    let c_code = std::fs::read_to_string(&path)?;
                    Self::from_c_code(&headers_folder, &path, name, &c_code)
                },
            )
            .collect::<Result<Vec<_>, _>>()?;

        Ok(headers)
    }

    fn from_c_code(
        headers_folder: &Path,
        path: &Path,
        name: &str,
        c_code: &str,
    ) -> Result<Self, Box<dyn std::error::Error + Send + Sync>> {
        let name_snake_case = name
            .strip_prefix("ofx")
            .unwrap()
            .to_case(convert_case::Case::Snake);

        let mut info: AdditionalInfo = Default::default();

        let mut included_headers = HashSet::new();
        for line in c_code.lines() {
            static INCLUDE_PREFIX: &str = "#include \"";
            static INCLUDE_SUFFIX: &str = ".h\"";

            if line.starts_with(INCLUDE_PREFIX) && line.ends_with(INCLUDE_SUFFIX) {
                let include_name =
                    line[(INCLUDE_PREFIX.len())..(line.len() - INCLUDE_SUFFIX.len())].to_string();

                if include_name == COLORSPACE_HEADER_NAME {
                    continue;
                }
                included_headers.insert(include_name);
            }
        }

        let mut additional_rust_code: Option<String> = None;
        if name == "ofxCore" {
            additional_rust_code = Some(SpecialCasingForStatuses::gen_additional_code(
                &mut info, c_code,
            )?);
        } else {
            included_headers.insert("ofxCore".to_string());
        }

        Ok(Header {
            name: name.to_owned(),
            mod_name_snake_case: name_snake_case,
            included_headers,
            bindgen_generated_rust_code: bindgen::Builder::default()
                .header("stdbool.h")
                .header(headers_folder.join("ofxCore.h").to_string_lossy())
                .header(path.to_string_lossy())
                .allowlist_function("") // blocking all
                .allowlist_type("Ofx.+")
                .allowlist_var("kOfx.+")
                .generate_cstr(true)
                .generate()?
                .to_string(),
            additional_rust_code,
            additional_info: info,
        })
    }
}

struct ProcessOutput {
    deduplicated_syn_files: HashMap<String, syn::File>,
    checks_syn_files: HashMap<String, syn::File>,
    root_item_idents_per_header: HashMap<String, HashSet<String>>,
    c_enums: HashMap<String, HashSet<String>>,
    suites: HashMap<String, HashSet<String>>,
}

fn process(headers: &[Header]) -> Result<ProcessOutput, Box<dyn std::error::Error>> {
    // item name -> `mod_name_snake_case` of the header file that defines it
    let mut seen_names: HashMap<String, String> = HashMap::new();

    let mut deduplicated_syn_files: HashMap<String, syn::File> = HashMap::new();
    let mut checks_syn_files: HashMap<String, syn::File> = HashMap::new();
    let mut root_item_idents_per_header: HashMap<String, HashSet<String>> = HashMap::new();
    let mut c_enums: HashMap<String, HashSet<String>> = HashMap::new();
    let mut suites: HashMap<String, HashSet<String>> = HashMap::new();

    for header in headers {
        let syn_file = syn::parse_file(&header.bindgen_generated_rust_code)?;

        // `check_items`: `const _: () = { … };`
        let (items, check_items) = syn_file.items.iter().partition::<Vec<_>, _>(
            |item| !matches!(item, syn::Item::Const(item_const) if item_const.ident == "_"),
        );

        checks_syn_files.insert(
            header.name.clone(),
            syn::File {
                items: check_items.into_iter().cloned().collect(),
                shebang: None,
                frontmatter: None,
                attrs: vec![],
            },
        );

        // `mod_name_snake_case` -> item names
        let mut dup_names: HashMap<String, HashSet<String>> = HashMap::new();
        let mut dedup_items: Vec<syn::Item> = vec![];
        for (ident, item) in collect_root_item_idents_per_header(&items) {
            let name = ident.to_string();
            if let Some(mod_name) = seen_names.get(&name) {
                dup_names
                    .entry(mod_name.clone())
                    .or_default()
                    .insert(name.clone());
            } else {
                seen_names.insert(name.clone(), header.mod_name_snake_case.clone());
                let mut item = item.clone();
                SpecialCasingForCEnums::process_relevant_item(&mut item, &mut c_enums)?;
                SpecialCasingForSuites::record_relevant_item(&item, &mut suites)?;
                dedup_items.push(item);
                root_item_idents_per_header
                    .entry(header.mod_name_snake_case.clone())
                    .or_default()
                    .insert(name);
            }
        }

        let mut syn_files = syn::File {
            items: dedup_items,
            ..syn_file
        };

        let used_idents = collect_idents(&syn_files);

        for set in dup_names.values_mut() {
            set.retain(|name| used_idents.contains(name));
        }

        let mut use_items: Vec<(String, syn::Item)> = vec![];
        for (mod_name, names) in dup_names {
            if names.is_empty() {
                continue;
            }

            let mut names: Vec<&String> = names.iter().collect();
            names.sort();

            let use_item = make_use_item(&mod_name, &names);

            use_items.push((mod_name.clone(), syn::Item::Use(use_item)));
        }
        use_items.sort_by(|(mod_name_a, _), (mod_name_b, _)| mod_name_a.cmp(mod_name_b));

        syn_files
            .items
            .splice(0..0, use_items.into_iter().map(|(_, item)| item));

        deduplicated_syn_files.insert(header.name.clone(), syn_files);
    }

    Ok(ProcessOutput {
        deduplicated_syn_files,
        checks_syn_files,
        root_item_idents_per_header,
        c_enums,
        suites,
    })
}

fn collect_root_item_idents_per_header<'a>(
    items: &[&'a syn::Item],
) -> Vec<(&'a syn::Ident, &'a syn::Item)> {
    items
        .iter()
        .filter_map(|item| {
            let ident = match item {
                syn::Item::Const(item_const) => &item_const.ident,
                syn::Item::Fn(item_fn) => &item_fn.sig.ident,
                syn::Item::Struct(item_struct) => &item_struct.ident,
                syn::Item::Type(item_type) => &item_type.ident,
                syn::Item::Enum(_)
                | syn::Item::ExternCrate(_)
                | syn::Item::ForeignMod(_)
                | syn::Item::Impl(_)
                | syn::Item::Macro(_)
                | syn::Item::Mod(_)
                | syn::Item::Static(_)
                | syn::Item::Trait(_)
                | syn::Item::TraitAlias(_)
                | syn::Item::Union(_)
                | syn::Item::Use(_) => {
                    panic!("unexpected item: {}", quote! { #item })
                }
                syn::Item::Verbatim(_) => panic!("unexpected verbatim item: {}", quote! { #item }),
                _ => panic!("unexpected unknown item: {}", quote! { #item }),
            };

            if SpecialCasingForStatuses::should_skip_ident(ident) {
                None
            } else {
                Some((ident, *item))
            }
        })
        .collect()
}

fn collect_idents(syn_file: &syn::File) -> HashSet<String> {
    struct IdentVisitor {
        idents: HashSet<String>,
    }
    impl<'a> syn::visit::Visit<'a> for IdentVisitor {
        fn visit_ident(&mut self, ident: &syn::Ident) {
            self.idents.insert(ident.to_string());
        }
    }

    let mut visitor = IdentVisitor {
        idents: HashSet::new(),
    };
    syn::visit::visit_file(&mut visitor, syn_file);

    visitor.idents
}

fn make_use_item(mod_name: &str, names: &[&String]) -> syn::ItemUse {
    syn::ItemUse {
        attrs: vec![],
        vis: syn::Visibility::Inherited,
        use_token: Default::default(),
        leading_colon: None,
        tree: syn::UseTree::Path(syn::UsePath {
            ident: syn::Ident::new("super", proc_macro2::Span::call_site()),
            colon2_token: Default::default(),
            tree: Box::new(syn::UseTree::Path(syn::UsePath {
                ident: syn::Ident::new(mod_name, proc_macro2::Span::call_site()),
                colon2_token: Default::default(),
                tree: Box::new(syn::UseTree::Group(syn::UseGroup {
                    brace_token: Default::default(),
                    items: names
                        .iter()
                        .map(|name| {
                            syn::UseTree::Name(syn::UseName {
                                ident: syn::Ident::new(name, proc_macro2::Span::call_site()),
                            })
                        })
                        .collect(),
                })),
            })),
        }),
        semi_token: Default::default(),
    }
}

struct SpecialCasingForStatuses;
impl SpecialCasingForStatuses {
    fn gen_additional_code(
        info: &mut AdditionalInfo,
        c_code: &str,
    ) -> Result<String, Box<dyn std::error::Error + Send + Sync>> {
        let mut additional_lines: Vec<String> = vec![];

        for line in c_code.lines() {
            const PREFIX: &str = "#define kOfxStat";
            if !line.starts_with(PREFIX) {
                continue;
            }
            let rest = line[PREFIX.len()..].trim();
            let (name, rest) = rest
                .split_once(' ')
                .ok_or_else(|| format!("Failed to split line: {}", line))?;
            info.statuses.insert(name.to_string());
            let num = extract_number(rest)
                .ok_or_else(|| format!("Failed to extract number from line: {}", line))?;
            additional_lines.push(format!("pub const kOfxStat{}: OfxStatus = {};", name, num));
        }

        Ok(additional_lines.join("\n"))
    }

    fn should_skip_ident(ident: &syn::Ident) -> bool {
        // included in `additional_rust_code`.
        ident == "kOfxStatOK"
    }
}

struct SpecialCasingForCEnums;
impl SpecialCasingForCEnums {
    fn process_relevant_item(
        item: &mut syn::Item,
        c_enums: &mut HashMap<String, HashSet<String>>,
    ) -> Result<(), Box<dyn std::error::Error>> {
        let syn::Item::Const(item) = item else {
            return Ok(());
        };
        let ident_str = item.ident.to_string();
        let Some(underscore_index) = ident_str.rfind('_') else {
            return Ok(());
        };
        let k_name = &ident_str[underscore_index + 1..];
        if !ident_str.starts_with("Ofx") {
            if ident_str.starts_with("kOfxKey_") {
                return Ok(());
            }
            return Err(format!("unrecognized constant key name format: {}", ident_str).into());
        }
        if !k_name.starts_with("kOfx") {
            return Err(format!("unrecognized constant key name format: {}", ident_str).into());
        }
        let ty_str = item.ty.to_token_stream().to_string();
        if !ty_str.starts_with("Ofx") {
            return Err(format!("not an enum?: {:?}", item.to_token_stream()).into());
        }
        item.ident = syn::Ident::new(k_name, item.ident.span());
        c_enums
            .entry(ty_str)
            .or_default()
            .insert(k_name.to_string());

        Ok(())
    }
}

struct SpecialCasingForSuites;
impl SpecialCasingForSuites {
    fn record_relevant_item(
        item: &syn::Item,
        suites: &mut HashMap<String, HashSet<String>>,
    ) -> Result<(), Box<dyn std::error::Error>> {
        let syn::Item::Struct(item) = item else {
            return Ok(());
        };
        let ident_str = item.ident.to_string();
        if !ident_str.rfind("SuiteV").is_some() {
            return Ok(());
        }
        let fns: HashSet<String> = item
            .fields
            .iter()
            .filter_map(|field| field.ident.as_ref().map(|ident| ident.to_string()))
            .collect();

        suites.entry(ident_str).or_default().extend(fns);

        Ok(())
    }
}

impl DependencySortable for Header {
    fn name(&self) -> &str {
        &self.name
    }

    fn dependencies(&self) -> &HashSet<String> {
        &self.included_headers
    }
}

fn extract_number(input: &str) -> Option<u32> {
    let mut i_start = -1;
    let mut i_end = -1;

    for (i, ch) in input.chars().enumerate() {
        if ch.is_ascii_digit() {
            if i_start == -1 {
                i_start = i as i32;
            }
            i_end = i as i32;
        } else if i_start != -1 {
            break;
        }
    }

    if i_start == -1 || i_end == -1 {
        None
    } else {
        let number_str = &input[i_start as usize..=i_end as usize];
        Some(number_str.parse::<u32>().unwrap())
    }
}
