generated-c-bindings-path := "generated/c_bindings"
generated-code-from-path := "generated/code_from_cpp"
generated-code-from-cpp-path := "generated/code_from_cpp"

generate:
    rm -rf {{ generated-c-bindings-path }}
    rm -rf {{ generated-code-from-path }}
    rm -rf {{ generated-code-from-cpp-path }}
    mkdir -p {{ generated-c-bindings-path }}
    mkdir -p {{ generated-code-from-path }}
    mkdir -p {{ generated-code-from-cpp-path }}
    cargo run --release --package openfx-bindgen --bin openfx-bindgen -- \
      --input-c-headers "vendor/openfx/include" \
      --output-c-bindings "{{ generated-c-bindings-path }}"

publish: generate
    cargo publish
